### ISSUE TITLE
nats-bench panics when message amount is 0

### ISSUE THREAD

**Issue by arekkas** [nats-io/nats#227]
```
go run nats-bench.go -n 0 msg.test
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x5f9940, 0xc042008070)
        C:/Go/src/runtime/panic.go:500 +0x1af
main.main()
        D:/workspace/go/src/github.com/nats-io/nats/examples/nats-bench.go:76 +0x68e
exit status 2
```

**Comment by aricart** [comment]
The `-n` flag is number of messages. Not message size.

**Comment by arekkas** [comment]
thanks, i already updated the title :)
